class Recipient:
    @classmethod
    def from_str(cls, recipient_string: str) -> Recipient: ...

class Identity:
    @classmethod
    def generate(cls) -> Identity: ...
    @classmethod
    def from_str(cls, identity_string: str) -> Identity: ...
    def to_public(self) -> Recipient: ...
