#!jinja|yaml|age

# passphrase: secret
# private: |
#   -----BEGIN AGE ENCRYPTED FILE-----
#   YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNjcnlwdCByVHVqQ1VqZTJoUE5pSUJW
#   Q21ldWt3IDE4CkZycDNnekhtNGIwRlMwMUsrUUlBMDhwVWEyd0pMcGpYUFFhRlVl
#   TUV2Y0kKLS0tIDFkK3JSdmJyR0kxSGpmSGFtRDExZGFwRWN5dEh6cWZJL3I2N05P
#   QTdTbmcKaT4kjwGgKX8AtIYINIDtiWt2dFYprN0cyp00fWweZkcyUuUFqQ==
#   -----END AGE ENCRYPTED FILE-----


private: |
  -----BEGIN AGE ENCRYPTED FILE-----
  YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdFVjZXMzOTFCMEVpMkZL
  N0tlbWg1UVA5MWRXbW9tUkd1YTcveW1DZ0FFCjJGREl4WHFPRmJoYVJRZSt6SGNr
  WjRNTXdSbXZsdkdDVkN5M0Nab2tOV2MKLS0tIFllZGFYRi9FaHlGbEJrcXp2bml3
  MWtaWHgwWlhHZ2pxcXhIWVlQQmNtY1kK0T4nDRHREH1eSH6XfRE3bbXs9sy194A5
  P+muFBaHfFSZsNvBGco=
  -----END AGE ENCRYPTED FILE-----

public: that's not a secret
