name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: read

jobs:

  pypi-publish:
    name: PyPI Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - id: version
        run: echo "version=$(grep -oP '^version = \"\K(\d+\.\d+\.\d+)' pyproject.toml)" >> "$GITHUB_OUTPUT"
      - run: test "$GITHUB_REF_NAME" = "${{ steps.version.outputs.version }}"
      - run: uv sync --locked
      - run: uv run ruff format --check
      - run: uv run ruff check
      - run: uv run basedpyright
      - run: uv run pytest -vvv
      - run: uv build
      - run: uv run --no-project --isolated --with dist/*.whl saltstack-age --help
      - run: uv run --no-project --isolated --with dist/*.tar.gz saltstack-age --help
      - run: uv publish --check-url https://pypi.org/simple/ --token ${{ secrets.SALTSTACK_AGE_PYPI_TOKEN }}
